#!/bin/sh

# Auto format the code
if ! [ -x "$(command -v swift)" ]; then
  echo 'Error: swift is not installed.' >&2
  echo 'You should install it before continuing' >&2
  exit 1
fi

if ! [ -x "$(command -v swift-format)" ]; then
  echo 'Error: swift-format is not installed.' >&2
  git clone https://github.com/apple/swift-format.git /tmp/__hawkci__/swift-format
  cd /tmp/__hawkci__/swift-format
  swift build -c release
  cp .build/release/swift-format /Applications/Xcode.app/Contents/Developer/usr/bin
  ln -s /Applications/Xcode.app/Contents/Developer/usr/bin/swift-format /usr/local/bin/swift-format
  cp .build/release/generate-pipeline /Applications/Xcode.app/Contents/Developer/usr/bin
  ln -s /Applications/Xcode.app/Contents/Developer/usr/bin/generate-pipeline /usr/local/bin/generate-pipeline
else
  echo "Linting..."
  git diff --diff-filter=d --cached --name-only | grep -E '\.(swift)$' | xargs -I{} swift-format -m lint --configuration .swift-format {}
  echo "Auto-Formatting..."
  git diff --diff-filter=d --cached --name-only | grep -E '\.(swift)$' | xargs -I{} swift-format -m format -r --configuration .swift-format -i {}
  echo "You might need to re-commit to commit the updated formmated code"
fi

if ! [ -x "$(command -v generate-enum-properties)" ]; then
  echo "Installing swift-enum-properties"
  git clone https://github.com/pointfreeco/swift-enum-properties.git /tmp/__hawkci__/swift-enum-properties
  cd /tmp/__hawkci__/swift-enum-properties
  make install
fi

#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
