name: Test PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build
    - name: Run tests
      run: make test
